### PR TITLE
[Done] translate community/support (related to #117)

### PR DESCRIPTION
**Pull request by Fcmam5**
Related to #117

### CODE REVIEW

**Comment by 3imed-jaberi** [comment]
## Hello @Fcmam5 , 
---
##  I think every page should be in one PR. Check out this with @iRayan7.
##  If this may be, i think you should rename this PR to `[Work in progress] translate community section`.
##  I will help here translate the rest together.

**Comment by Fcmam5** [comment]
> Hello @Fcmam5 ,
> think every page should be in one PR. Check out this with @iRayan7.
> If this may be, i think you should rename this PR to `[Work in progress] translate community section`.
> I will help here translate the rest together.

You're right about the title, I thought that it was a simple page until I figured out that it was a complete section.
And sure, you are the most welcome to collaborate on this section, just reference #113 on your PRs, or let's follow any strategy the team chooses :)

**Comment by 3imed-jaberi** [comment]
> > Hello @Fcmam5 ,
> > think every page should be in one PR. Check out this with @iRayan7.
> > If this may be, i think you should rename this PR to `[Work in progress] translate community section`.
> > I will help here translate the rest together.
> 
> You're right about the title, I thought that it was a simple page until I figured out that it was a complete section.
> And sure, you are the most welcome to collaborate on this section, just reference #113 on your PRs, or let's follow any strategy the team chooses :)

### Awesome, let's wait for the strategy of the team to choose 🤝:heart:
### @iRayan7

**Comment by iRayan7** [comment]
@Fcmam5 Please make this PR for the first page to close it 👍

**Pull request merged**
