### PR TITLE
Translating hello-world.md

### PR DESCRIPTION
**Pull request by IsraaMoqbel**

### CODE REVIEW

**Comment by asantarissy** [comment]
@IsraaMoqbel What's the status on this?

**Comment by IsraaMoqbel** [comment]
> @IsraaMoqbel What's the status on this?

sorry, I was trying to figure some things out in github, 
I'm done with it, but I hope I can get some feedback about my translation or if there's any things you think I should change, I'm new to translating =D @asantarissy

**Comment by asantarissy** [comment]
Looks good @IsraaMoqbel يعطيكي العافيه

But I'd recommend you to check [hsoub translations for this page](https://wiki.hsoub.com/React/hello_world) as they are using more accurate terms 😃 

Also we need to keep the English terms, i.e React, Javascript, etc.

Finally, Please pull the master from this repo to your branch, RTL is now active, and you'll find that you won't be needing to translate the "Try it on CodePen" or "Edit this page".

Enjoy!

**Comment by IsraaMoqbel** [comment]
> Looks good @IsraaMoqbel يعطيكي العافيه
الله يعافيك يا رب

> But I'd recommend you to check [hsoub translations for this page](https://wiki.hsoub.com/React/hello_world) as they are using more accurate terms 

Their translation is awesome! I feel ashamed of my own translation :face_with_head_bandage: I want to die :hocho: :disappointed: 
why don't you ccontact hsoub and rely on their translation?

**Comment by Emmanuel-Melon** [comment]
It's quite possible but I recommend attempting translation on your own and
using their Wiki as a reference. Translating the docs by yourself will give
you a multi perspective understanding of certain topics.

**Comment by asantarissy** [comment]
> > Looks good @IsraaMoqbel يعطيكي العافيه
> 
> الله يعافيك يا رب
> 
> > But I'd recommend you to check [hsoub translations for this page](https://wiki.hsoub.com/React/hello_world) as they are using more accurate terms
> 
> Their translation is awesome! I feel ashamed of my own translation 🤕 I want to die 🔪 😞
> why don't you contact hsoub and rely on their translation?
> 
> > you'll find that you won't be needing to translate the "Try it on CodePen" or "Edit this page".
> 
> Beg your pardon, but does this mean that I should be removing the link completely?

No @IsraaMoqbel  don't be, what you did is really good 💪 

I agree with @Emmanuel-Melon we don't won't to copy what hsoub did, trust me you will gain more knowledge when you do it yourself, and use hsoub as a reference.

I'll add some review comments to explain what I meant for the "Try it on CodePen" part

**Comment by IsraaMoqbel** [comment]
When I come across a sentence that whether to translate it with my own rephrasing and my own words or translating it literally in both ways it will make a sense, I believe that it's more convenient to use native language rephrasing than just literally translating words, BUT I usually tend to stick to the literal translation because I think this would be more accurate and more professional! what do you think? @asantarissy

**Comment by Emmanuel-Melon** [comment]
The main goal here is to create docs that make sense to native speakers.
Feel free to use your own words. I also think that this is contextual, some
terms require literal translation while others could be interpreted in
different ways.
For example, functions should translate to nothing but "دوال" or else it
wouldn't make sense.

**Comment by asantarissy** [comment]
Hello @IsraaMoqbel, @iRayan7 created a new [Glossary wiki](https://github.com/reactjs/ar.reactjs.org/wiki/Glossary), please use it as a reference and keep checking it as it's WIP.

Cheers!

**Comment by iRayan7** [comment]
Hi @IsraaMoqbel, any updates on this?

**Pull request closed without merging**
