### PR TITLE
Start Translating faq-build.md & faq-functions.md

### PR DESCRIPTION
**Pull request by AbdelkhalekESI**
Work in progress ....

### CODE REVIEW

**Comment by iRayan7** [comment]
Hi @AbdelkhalekESI, any updates?

**Comment by AbdelkhalekESI** [comment]
@iRayan7 Work In progress !

**Comment by iRayan7** [comment]
Hi @AbdelkhalekESI, any update?

**Comment by iRayan7** [comment]
Hello @AbdelkhalekESI, any updates on this? Please reply before the end of this week or I will have to re-assign these pages. Thanks.

**Comment by 3imed-jaberi** [comment]
Hey @iRayan7 , i will take the pages of @AbdelkhalekESI if there is no response ..

**Comment by iRayan7** [comment]
@3imed-jaberi Go for it 👍closing this PR.... Please open up a new PR and assign your self in #1. Thanks.

**Pull request closed without merging**
