### PR TITLE
Translating lists-and-keys.md

### PR DESCRIPTION
**Pull request by splimter**
Translating **list-and-kesy.md** file.

### CODE REVIEW

**Comment by splimter** [comment]
Review on what ??

**Comment by asantarissy** [comment]
> Review on what ??

@splimter every PR should go through some sort of a review process, if everything is okay one of the maintainers will merge it. I'm assigned to this PR, I'll review it and let you know if I have any comments.

**Comment by asantarissy** [comment]
Good job @splimter, but could you please refer to [Hsoub Page](https://wiki.hsoub.com/React/lists_and_keys) and update your PR accordingly.

**Comment by splimter** [comment]
is there anything to change

**Pull request closed without merging**
