### PR TITLE
Translating rendering-elements.md

### PR DESCRIPTION
**Pull request by omar-dulaimi**

### CODE REVIEW

**Comment by asantarissy** [comment]
@omar-dulaimi what's the status on this?

**Comment by omar-dulaimi** [comment]
> @omar-dulaimi what's the status on this?

Hey @asantarissy sorry for the wait, I will upload new changes by the end of today fo sure. And I might ask for another page if you like my translation.

**Comment by asantarissy** [comment]
> > @omar-dulaimi what's the status on this?
> 
> Hey @asantarissy sorry for the wait, I will upload new changes by the end of today fo sure. And I might ask for another page if you like my translation.

That's great @omar-dulaimi 💪🏼
Let me know if you need any help.

**Comment by asantarissy** [comment]
Hello @omar-dulaimi, @iRayan7 created a new [Glossary wiki](https://github.com/reactjs/ar.reactjs.org/wiki/Glossary), please use it as a reference and keep checking it as it's WIP.

Cheers!

**Comment by Emmanuel-Melon** [comment]
Hey, it's Emmanuel here, currently translating the tutorial page (PR #4).
Sorry for the extreme delay. I got so caught up with a project I'm
working on. But today's a weekend and I'm back to translating. Will push my
changes once I'm finished.

Regards,
Emmanuel.

**Comment by asantarissy** [comment]
Hello @omar-dulaimi, what's the status? should we assign it to another contributor?

**Comment by omar-dulaimi** [comment]
Hey @asantarissy  I'm sorry it just got so busy these days that I'm not on github a lot anymore. I will try my best to do it as soon as possible

**Comment by iRayan7** [comment]
Hi @omar-dulaimi, any updates?

**Comment by omar-dulaimi** [comment]
Hey @iRayan7 I will push it once I get home today, sorry for the long wait I just had been really busy lately

**Comment by iRayan7** [comment]
Amazing work @omar-dulaimi 👏

**Comment by omar-dulaimi** [comment]
@iRayan7 thank you

**Pull request merged**
