### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by atefBB**
<div dir="rtl">أقترح استبدال لفظ خادم بخادوم فهي أفصح.</div>

### CODE REVIEW

**Review by asantarissy — APPROVED** [review]
LGTM 🚀

**Comment by atefBB** [comment]
@asantarissy I propose to modify the translation of `server` in `Arabic`. Your thoughts?

**Comment by asantarissy** [comment]
> @asantarissy I propose to modify the translation of `server` in `Arabic`. Your thoughts?

Thanks @atefBB yes I agree `خادوم` is better، yet `خادم` is the most used word according to [Wikipedia Server Page](https://ar.wikipedia.org/wiki/%D8%AE%D8%A7%D8%AF%D9%85_(%D8%AD%D9%88%D8%B3%D8%A8%D8%A9))

**Comment by atefBB** [comment]
I'll send another PR fixing the server translation -in shaa Allah-

**Pull request merged**
