### PR TITLE
Begin file translation

### PR DESCRIPTION
**Pull request by atefBB**

### CODE REVIEW

**Comment by iRayan7** [comment]
Hi Atef, this file has been translated and waiting for review right now https://github.com/reactjs/ar.reactjs.org/pull/55
🙏 Please check the steps here https://github.com/reactjs/ar.reactjs.org#steps

**Comment by atefBB** [comment]
Sorry for that ! Can i review it there?

**Comment by iRayan7** [comment]
Yes, sure! please note that it's based on Hsoub's translation of that page 👍

**Comment by atefBB** [comment]
Thank you.

**Comment by iRayan7** [comment]
Thank you, Atef! 
Would love to see you take on another page if possible 🙏

**Comment by atefBB** [comment]
I'll do when have some time!

**Pull request closed without merging**
